src/App.js, src/navbar.js
=> add a navbar because we deserve a home button

src/components/Home/index.js
=> small UI improvement for home page, links are buttons

src/components/NewStudentForm/index.js
It just wouldn't be a real web app without last-minute updates before the demo 😂
=> add other dances and classes multi check box fields

src/components/Home/index.js, src/components/NewStudentForm/index.js, src/navbar.js
=> other input text and misc

src/components/ReturningStudentForm/index.js
=> let user enter payment type on checkin

.firebaserc, .gitignore, TODO.md, database.rules.json, firebase.json, package-lock.json, package.json, src/components/DanceCheckinForm/index.js, src/components/DanceForm/index.js, src/components/Home/index.js, src/components/NewStudentForm/index.js, src/components/ReturningStudentForm/index.js, src/components/User/index.js, src/index.js, src/lib/api.js, src/navbar.js, src/routes.js, src/types.js, yarn.lock
Added user auth so that the DB doesn't have to be exposed to the
world. Connected forms to the DB.
Things that aren't done: see TODO
=> this is what happens when I don't finish what I start

package.json, src/navbar.js, yarn.lock
Had to update reactstrap to latest because dropdowns in the nav weren't working.
=> clean up nav

TODO.md, src/lib/api.js, src/navbar.js, src/types.js
=> sign every DB action

TODO.md, src/components/DanceCheckinForm/form.js, src/components/DanceCheckinForm/index.js, src/components/DanceForm/index.js, src/components/Home/index.js, src/components/NewStudentForm/form.js, src/components/NewStudentForm/index.js, src/components/ReturningStudentForm/form.js, src/components/ReturningStudentForm/index.js, src/components/Students/index.js, src/components/Users/index.js, src/components/Users/new.js, src/lib/api.js, src/lib/utils.js, src/navbar.js, src/routes.js
Also reorganized the forms a little bit.
=> update student info, update dance info

TODO.md, src/components/NewStudentForm/form.js, src/components/NewStudentForm/index.js, src/components/ReturningStudentForm/form.js, src/components/ReturningStudentForm/index.js, src/lib/api.js, src/navbar.js, src/routes.js
* Update TODO
* Fixed a bug with the date picker data being reformatted to a string in the class checkin API call
* Changed API endpoint name from "returning" to "class-checkin"
* Updated nav bar links
=> new student redirect to class checkin form with student data

src/components/Home/index.js, src/components/NewStudentForm/form.js, src/components/NewStudentForm/index.js, src/components/ReturningStudentForm/form.js, src/components/ReturningStudentForm/index.js, src/components/Utilities/confirmButton.js, src/routes.js, src/types.js
* Class checkin confirmation modal
* Add a note to the class checkin if the person is a new dancer, redirected from the new student page
* Updated broken link in home page
* Added a catch-all route that redirects to home page
* Fixed student wording
* Added student boolean to class checkin
* Class checkin submit button only renders if the email is entered
* After class checkin confirmation, redirects to home page
=> class checkin confirmation modal, new dancer note

.gitignore, TODO.md, src/components/DanceCheckinForm/form.js, src/components/NewStudentForm/form.js, src/components/NewStudentForm/index.js, src/components/ReturningStudentForm/form.js, src/components/Students/checkins.js, src/components/Students/index.js, src/components/Students/infoForm.js, src/components/Utilities/alert.js, src/components/Utilities/conductModal.js, src/components/Utilities/confirmButton.js, src/components/Utilities/waiverModal.js, src/types.js
* Fixed: Clear warning "Links must not point to '#'. Use a more descriptive href or use a button instead"
* Cleaned up some console.log lines
* Modal for code of conduct-- must agree to modal, includes short text, pulled from https://missioncityswing.com/about/coc/
* Modal for waiver-- must agree to modal, waiting on real wavier text
=> Updated .gitignore, added code of conduct, a couple other things

TODO.md, src/components/ReturningStudentForm/form.js, src/components/Students/checkins.js, src/lib/api.js, src/lib/utils.js, src/types.js
* Can see if a student has paid for a monthly pass for that month and how many classes they've paid for (1 or 2)
* Can view monthly pass status when the student checks in for class and on their profile-update page
Implementation details:
* Monthly pass status updates when the student checks in for monthly pass classes for the first time that month
* Monthly pass status is a child object on the student profile
=> some monthly pass logic, probably needs a second pass

TODO.md, database.rules.json, package.json, src/components/DanceForm/checkins.js, src/components/DanceForm/index.js, src/components/Students/checkins.js, src/components/Students/index.js, src/index.js, src/lib/api.js, src/lib/utils.js, yarn.lock
* Cleaned up tables for class and dance checkin history-- new tables include sorting and filtering
* Fixed a bug with the drop-down list of dances not being sorted
=> nice tables for checkin lists and sorted dances list

TODO.md, database.rules.json, src/components/DanceCheckinForm/form.js, src/components/DanceCheckinForm/index.js, src/components/DanceForm/checkins.js, src/components/DanceForm/index.js, src/components/NewStudentForm/form.js, src/components/NewStudentForm/index.js, src/components/ReturningStudentForm/form.js, src/components/ReturningStudentForm/index.js, src/components/Students/checkins.js, src/components/Students/index.js, src/components/Students/infoForm.js, src/components/Utilities/conductModal.js, src/components/Utilities/confirmCheckinModal.js, src/components/Utilities/waiverModal.js, src/lib/api.js, src/lib/utils.js, src/navbar.js, src/types.js
* Fixed: "Returning students" need to say "Class checkin"
* Fixed: West coast swing needs to be on the dances list
* Fixed: Only people new to WCS get the discount-- need to update "New Dancer" note logic
* Fixed: For a dance event, show the total number of people checked into the class and/or dance
* Fixed: Put the year with the month for the last monthly pass
* Fixed: Pre fill out classes if the student has a monthly pass for N classes for M months-- look up the class that they got the pass with
* Fixed: Want to be able to pre-load guests— maybe have "guest" as a field in the student profile
* Fixed: Do the waiver and CoC need to show up again if the student has already agreed to them?-- would be better if there were fewer items on the page
* Fixed: If you click on the waiver and CoC …
=> completed list of todo items from 2018-06-20 sync

.gitignore, src/components/DanceCheckinForm/form.js, src/components/DanceCheckinForm/index.js, src/components/Home/index.js, src/components/NewStudentForm/form.js, src/components/ReturningStudentForm/form.js, src/components/ReturningStudentForm/index.js, src/index.css, src/navbar.js
* Fixed bug where dance checkin doesn't show patrons list
* Made home page cards the same height, gave them bottom margins
* Added to the .gitignore
* Fixed where I left out URI encoding for success/error messages
* Made the logo smaller so it looks better on small screens
=> fix bug where dance checkin doesn't show patrons list

TODO.md, database.rules.json, src/components/DanceCheckinForm/form.js, src/components/Home/index.js, src/components/NewStudentForm/form.js, src/components/ReturningStudentForm/form.js, src/components/Students/index.js, src/components/Students/infoForm.js, src/lib/api.js, src/lib/utils.js, src/types.js
[x] Added: birthday on new student form
[x] Added: 'member since' on profile form because it would be a shame to lose that historical info for our members, defaults to today, stealthily added for profiles added during class or dance checkins
[x] Fixed: On the home page, even after you close the alert, if you refresh the page, the alert shows up again
[x] Fixed: Profile updates overriding admin info and cached latest monthly pass
=> added birthday for form and fixed some bad bugs

TODO.md, src/components/NewStudentForm/form.js
When you enter the name of the referral, the option box
should get checked automatically.
=> referral and other box text checks main

TODO.md, src/components/DanceCheckinForm/form.js, src/components/DanceForm/form.js, src/components/NewStudentForm/form.js, src/components/ReturningStudentForm/form.js, src/components/Utilities/appDate.js, src/index.css, src/lib/api.js, src/navbar.js
Set default date across the app in a date dropdown in the nav bar
and save in a cookie that expires in 24 hours.
=> set default date across the app

TODO.md, src/components/NewStudentForm/adminForm.js, src/lib/api.js
Also removed some console.log calls and added calls to getAppDate.
[~] Safety around adding data-- should not overwrite fields not included in form, specifically thinking about [x] new student form
[ ] Typeahead for checking into dance
[ ] Square integration
=> safe writes for create-or-update student forms

TODO.md, src/components/DanceCheckinForm/form.js, src/components/DanceForm/form.js, src/components/NewStudentForm/adminForm.js, src/components/NewStudentForm/form.js, src/components/ReturningStudentForm/form.js, src/components/Utilities/appDateForm.js, src/lib/api.js, src/lib/utils.js
[x] Date dropdown doesn't work after information is auto-filled-- discovered this was an issue with the date not being parsed correctly
[~] Safety around adding data-- should not overwrite fields not included in form, specifically thinking about [x] new student form
[ ] Typeahead for checking into dance
[ ] Square integration
=> Updates from bugs found during Task Rabbit session

TODO.md, package.json, src/components/DanceCheckinForm/form.js, src/components/ReturningStudentForm/form.js, src/components/Students/index.js, src/index.js, yarn.lock
[~] Safety around adding data-- should not overwrite fields not included in form, specifically thinking about [x] new student form
[x] Typeahead for checking into dance
[ ] Square integration
=> Add typeahead to find returning students and dancers in dance and class checkin forms

package.json, src/components/NewStudentForm/adminForm.js, src/components/Utilities/alert.js, yarn.lock
Just a nice-to-have for entering a bunch of forms
=> add timeout for success alert

TODO.md, public/index.html, src/components/DanceCheckinForm/form.js, src/components/DanceCheckinForm/index.js, src/components/DanceForm/checkins.js, src/components/Home/index.js, src/components/ReturningStudentForm/form.js, src/components/ReturningStudentForm/index.js, src/components/Students/checkins.js, src/navbar.js
Checkin isn't a commonly used word and Joel has been reading it as "chicken" so he made me change it.
https://writingexplained.org/check-in-or-checkin
=> Changed checkin to check-in for viewable pages.

LICENSE
=> Add GNU GPL

TODO.md, src/components/ReturningStudentForm/form.js
TIL some javascript templated string literals. 
Once I have access to the firebase project I should be able to spin up a local instance and test?
=> #69 check-in confirmation to show full name, not email

src/components/ReturningStudentForm/form.js
Fixes https://github.com/missmaggiemo/mcs_registration/issues/78
=> Remove the confirmation button when students check in

src/components/ReturningStudentForm/form.js
=> Add class names to confirmation message

functions/src/index.ts
Node 8 (which we use) uses a different function signature for https
=> Fix function for node 8

package-lock.json, package.json, src/lib/api.js
@missmaggiemo For a new student form, it doesn't look like we record a class checkin for them. Is this something we want?
=> Add payment api

CODEOWNERS
Signed-off-by: Maggie Moreno <maggie.moreno@opendoor.com>
=> change code owners to team review

src/components/DanceCheckinForm/form.js, src/components/Home/adminIndex.js, src/components/NewStudentForm/form.js, src/components/ReturningStudentForm/form.js, src/components/Utilities/conductModal.js, src/components/Utilities/waiverModal.js, src/lib/api.js, src/types.js, yarn.lock
Changes:
- Added health attestation and vaccination check to class and dance check-in
- Updated waiver to include illness verbiage
- Updated class names (monthly -> 6-week series)
- Removed monthly pass logic from class check-in
- Removed student (as in, college student) check-box on check-in forms
- Fixed a bug re: intermediate class name showing up in class check-ins
=> Update MCS registration app for a post 2022 world

src/components/ClassSeriesForm/checkins.js, src/components/ClassSeriesForm/form.js, src/components/ClassSeriesForm/index.js, src/components/Home/adminIndex.js, src/lib/api.js, src/lib/utils.js, src/routes.js, src/types.js
At MCS, we recently revamped our class series and transitioned from 4-week series to 6-week series. We have found that that allows us to introduce more advanced content sooner with students! Check out more details here https://missioncityswing.com/classes-new-in-february-2022
These changes to the MCS app allow us to track which students are attending which series.
=> Add class series data model, API endpoints, view page, etc.

src/lib/api.js
Changes:
* fix new dancer info error re: val on undefined-- this was an annoying customer-facing bug
* add a note re: production DB to deploy-- note to self, really
* remove waiver check for new student form-- important because when I fill new sign-ups into the system from the sign-up Google form, they aren't present to agree to the waivers
=> Fix "val" error and other convenient changes

src/components/DanceCheckinForm/form.js, src/components/ReturningStudentForm/form.js, src/lib/api.js, src/types.js
=> update COVID booster blurb and hide if already agreed

src/components/BulkStudentEntryForm/form.js, src/components/BulkStudentEntryForm/index.js, src/components/Home/adminIndex.js, src/lib/api.js, src/routes.js
=> bulk entry page for new students form data

src/components/BulkStudentEntryForm/form.js, src/components/BulkStudentEntryForm/index.js, src/components/DanceCheckinForm/form.js, src/components/ReturningStudentForm/form.js, src/lib/api.js, src/types.js
As of April 5th, we are dropping our vaccination check policy, see announcement here https://www.facebook.com/groups/missioncityswing/posts/3550480425219572/
=> Remove vax check

src/components/BulkStudentEntryForm/checkinForm.js, src/components/BulkStudentEntryForm/index.js, src/lib/api.js
=> add another form field to bulk page for class check-ins
